### ISSUE TITLE
Get customer's metafields 

### ISSUE THREAD

**Issue by ortegafernando** [phpclassic/php-shopify#120]
Hi, I have the a problem with Customer(id)->Metafield->get()

I can get metafield with Advanced Rest Client Chrome Extension, so i dont know what is wrong here:

With post request:

`https://XXXXXXX@YYYYYY.myshopify.com/admin/api/2019-07/customers/2229915287661/metafields.json`

I get this:

`{ "metafields": [ { "id": 10766754480237, "namespace": "fiscal", "key": "VAT", "value": "tax_id_wholesale", "value_type": "string", "description": null, "owner_id": 2229915287661, "created_at": "2019-09-26T16:32:42-04:00", "updated_at": "2019-09-26T16:32:42-04:00", "owner_resource": "customer", "admin_graphql_api_id": "gid://shopify/Metafield/10766754480237" } ], }`

, but with:

`$data = $shopify->Customer(2229915287661)->Metafield->get();`

I get this;

`Fatal error: Uncaught PHPShopify\Exception\ApiException: Not Found in D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php:496 Stack trace: #0 D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php(315): PHPShopify\ShopifyResource->processResponse(Array, 'metafields') #1 D:\xampp\htdocs\process\customersAPI.php(10): PHPShopify\ShopifyResource->get() #2 {main} thrown in D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php on line 496`

Thanks

**Comment by ortegafernando** [comment]
Hi, I have also tried with a Product.

With (Advanced Rest Client Chrome extension)

`https://XXXXX:YYYYY@ZZZZZZ.myshopify.com/admin/api/2019-07/products/4033526431853/metafields.json`

I get

`{
"metafields": [
  {
"id": 10811794489453,
"namespace": "fiscal",
"key": "vat",
"value": "tax_id_wholesale",
"value_type": "string",
"description": null,
"owner_id": 4033526431853,
"created_at": "2019-09-29T13:11:03-04:00",
"updated_at": "2019-09-29T13:11:03-04:00",
"owner_resource": "product",
"admin_graphql_api_id": "gid://shopify/Metafield/10811794489453"
}
],
}`

With

`$data = $shopify->Product(4033526431853)->Metafield->get();`

I get:

`Fatal error: Uncaught PHPShopify\Exception\ApiException: Not Found in D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php:496 Stack trace: #0 D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php(315): PHPShopify\ShopifyResource->processResponse(Array, 'metafields') #1 D:\xampp\htdocs\process\customersAPI.php(10): PHPShopify\ShopifyResource->get() #2 {main} thrown in D:\xampp\htdocs\PHPShopify\phpclassic\php-shopify\lib\ShopifyResource.php on line 496`

Could anyone help me? Thanks
