### ISSUE TITLE
OpenSSL SSL_connect: SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by kaodouqifei** [phpclassic/php-shopify#235]
35 : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to deconovo-uk.myshopify.com:443  {"exception":"[object] (PHPShopify\\Exception\\CurlException(code: 0): 35 : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to deconovo-uk.myshopify.com:443  at D:\\phpstudy_pro\\WWW\\shopify\\vendor\\phpclassic\\php-shopify\\lib\\CurlRequest.php:179)
[stacktrace]
#0 D:\\phpstudy_pro\\WWW\\shopify\\vendor\\phpclassic\\php-shopify\\lib\\CurlRequest.php(84): PHPShopify\\CurlRequest::processRequest(Resource id #646)
#1 D:\\phpstudy_pro\\WWW\\shopify\\vendor\\phpclassic\\php-shopify\\lib\\HttpRequestJson.php(71): PHPShopify\\CurlRequest::get('https://a5dc6f6...', Array)
#2 D:\\phpstudy_pro\\WWW\\shopify\\vendor\\phpclassic\\php-shopify\\lib\\ShopifyResource.php(344): PHPShopify\\HttpRequestJson::get('https://a5dc6f6...', Array)
#3 D:\\phpstudy_pro\\WWW\\shopify\\app\\Jobs\\UpdateStock.php(88): PHPShopify\\ShopifyResource->get(Array)

What's the problem? How can I solve it? Has anyone encountered a similar problem？

**Comment by fabio-sassi-spotview** [comment]
Hi @kaodouqifei 

I found similar temporary problem in my log. 
```
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```
If I try again a moment later, same requests are ok.

I wrote a pull request #240 that implement a retry system to mitigate this kind of problem.
