### ISSUE TITLE
FulfillmentService post goes in Fatal error!!! D:

### ISSUE THREAD

**Issue by W3b3r** [phpclassic/php-shopify#31]
Hi guys,

i'm having problem with this code
```
$data	=	array (
	"fulfillment" => array("name" => "Hoplix Fulfillment Service",
					  "callback_url" => HTTP.HOST."/tracking",
					  "inventory_management" => false,
					  "tracking_support" => true,
					  "requires_shipping_method" => true,
					 ),
	);
$shopify->FulfillmentService->post($data);
```
The class return me Fatal Error with this message

`Fatal error:  Class 'PHPShopify\FulfillmentService' not found in /(path censured)/(path censured)/phpclassic/php-shopify/lib/ShopifySDK.php on line 202`

Thanks for your help.

**Comment by tareqtms** [comment]
Are you using composer or including files manually? If the later, please check if you have included the file for FulfillmentService class.

**Comment by W3b3r** [comment]
This is my include and require code

```
//request autoload
require PATH.'/classi/phpclassic/autoload.php';
//include file richiesti
include(PATH.'/classi/phpclassic/php-shopify/lib/ShopifySDK.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/AuthHelper.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Exception/CurlException.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Exception/SdkException.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Exception/ApiException.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/HttpRequestJson.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/CurlRequest.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/ShopifyResource.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Metafield.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/ProductImage.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/ProductVariant.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Product.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Order.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Event.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Fulfillment.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/FulfillmentEvent.php');
include(PATH.'/classi/phpclassic/php-shopify/lib/Shop.php');
```

**Comment by W3b3r** [comment]
Error when i try to delete Fulfillment Service Created
```
Fatal error:  Uncaught exception 'PHPShopify\Exception\CurlException' with message 'Request failed with HTTP Code 406.' in /home/sites/hoplix/classi/phpclassic/php-shopify/lib/ShopifyResource.php:485
Stack trace:
#0 /phpclassic/php-shopify/lib/ShopifyResource.php(414): PHPShopify\ShopifyResource->processResponse(NULL)
#1 /shopify-test.class.php(84): PHPShopify\ShopifyResource->delete(Array)
#2 /(path censured)/test/shopify.php(3): include('/home/sites/hop...')
#3 {main}
  thrown in /(path censured)/phpclassic/php-shopify/lib/ShopifyResource.php on line 485
```
Here the code that i call
`$shopify->FulfillmentService->delete(array("id" => "000000000")));`

**Comment by tareqtms** [comment]
This way only:
```
$shopify->FulfillmentService(000000000)->delete();
```

**Comment by W3b3r** [comment]
Works!
Thanks Tareq for support :D
