### ISSUE TITLE
Metafield on Product post

### ISSUE THREAD

**Issue by Lollichkeit** [phpclassic/php-shopify#323]
My Code:
```
...
$metafield = [
        'namespace' => "custom",
        'key' => "message",
        'value' => $message,
        'owner_resource' => "product",
        'owner_id' => $product_id,
        'value_type' => 'single_line_text_field',
];

$metafields = shopify->Product($product_id)->Metafield->post($metafield);
...
```

My Error:
`Fatal error: Uncaught PHPShopify\Exception\ApiException: Not Found in /home/svsqauxl/vendor/phpclassic/php-shopify/lib/ShopifyResource.php:540 Stack trace: #0 /home/svsqauxl/vendor/phpclassic/php-shopify/lib/ShopifyResource.php(419): PHPShopify\ShopifyResource->processResponse(Array, 'metafield') #1 /home/svsqauxl/www.svs-vertrieb.de/cronjobs/_src/shopify/elbsand/classes-new.php(213): PHPShopify\ShopifyResource->post(Array) #2 /home/svsqauxl/www.svs-vertrieb.de/cronjobs/shopify-elbsand.api.php(126): PHPProduct->updateMetaProducte() #3 {main} thrown in /home/svsqauxl/vendor/phpclassic/php-shopify/lib/ShopifyResource.php on line 540`

Please help me to upload the metadata.

**Comment by rossvor** [comment]
The type of error you are getting (Not Found) suggests that likely `$product_id` does not match any product on the store, so double check that you using the correct value there.

Also, provided metafield fields don't look right.
Should be something like this:
```
$metafield = [
        'namespace' => "custom",
        'key' => "message",
        'value' => $message,
        'type' => 'single_line_text_field',
];
```
Check the Shopify reference [here](https://shopify.dev/docs/api/admin-rest/2023-07/resources/metafield#Createametafieldforaproduct)

**Comment by ankesh4040** [comment]
@Lollichkeit Did it helped ? I am getting error Request failed with HTTP Code 400

**Comment by ankesh4040** [comment]
$metafieldv = 
         [     
        'namespace' => "custom",
        'key' => "features",
        'value' => "API updated",
        'type' => 'single_line_text_field'
         ]
    ;
    
    $metafields = $shopify->Product('7713539269680')->Metafield->post($metafieldv);
