### ISSUE TITLE
Product creation error after PHP8 update

### ISSUE THREAD

**Issue by Lollichkeit** [phpclassic/php-shopify#337]
I was able to upload products, but after switching to PHP 8 it no longer works.
I'm running this here:
`$shopify->Product->post($product);`
I pass this array:
```
Array(
    [body_html] => 
    [status] => active
    [tags] => Tags
    [vendor] => TESTERRERIEN
    [title] => TEST-WARE
    [product_type] => Test-Ware
)
```
And get this error:
```
<b>Fatal error</b>:  Uncaught PHPShopify\Exception\CurlException: Request failed with HTTP Code 400. in .../phpclassic/php-shopify/lib/HttpRequestJson.php:209
Stack trace:
#0 .../phpclassic/php-shopify/lib/HttpRequestJson.php(153): PHPShopify\HttpRequestJson::processResponse()
#1 .../phpclassic/php-shopify/lib/HttpRequestJson.php(86): PHPShopify\HttpRequestJson::processRequest()
#2 .../phpclassic/php-shopify/lib/ShopifyResource.php(417): PHPShopify\HttpRequestJson::post()
#3 .../classes.php(26): PHPShopify\ShopifyResource-&gt;post()
[...]
```
Please help me to find a solution

**Comment by Lollichkeit** [comment]
fixed
